#### IPL Match Prediction

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
deliveries = pd.read_csv('deliveries.csv')
match = pd.read_csv('matches.csv')

In [3]:
match.head(5)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [4]:
deliveries.head()

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals

In [5]:
match.shape,deliveries.shape

((950, 20), (225954, 17))

In [6]:
match['Season']=match['Season'].replace('2020/21','2020') 
match['Season']=match['Season'].replace('2009/10','2010') 
match['Season']=match['Season'].replace('2007/08','2008')
match['Season'].value_counts()

Season
2013    76
2022    74
2012    74
2011    73
2021    60
2020    60
2019    60
2018    60
2016    60
2014    60
2010    60
2017    59
2015    59
2008    58
2009    57
Name: count, dtype: int64

In [7]:
match['Venue']=match['Venue'].replace('Arun Jaitley Stadium, Delhi','Arun Jaitley Stadium') 
match['Venue']=match['Venue'].replace('Brabourne Stadium, Mumbai','Brabourne Stadium') 
match['Venue']=match['Venue'].replace('Dr DY Patil Sports Academy, Mumbai','Dr DY Patil Sports Academy') 
match['Venue']=match['Venue'].replace('Eden Gardens, Kolkata','Eden Gardens') 
match['Venue']=match['Venue'].replace('Feroz Shah Kotla','Arun Jaitley Stadium') 
match['Venue']=match['Venue'].replace('M.Chinnaswamy Stadium','M Chinnaswamy Stadium') 
match['Venue']=match['Venue'].replace('MA Chidambaram Stadium, Chepauk, Chennai','MA Chidambaram Stadium') 
match['Venue']=match['Venue'].replace('MA Chidambaram Stadium, Chepauk','MA Chidambaram Stadium') 
match['Venue']=match['Venue'].replace('Maharashtra Cricket Association Stadium, Pune','Maharashtra Cricket Association Stadium') 
match['Venue']=match['Venue'].replace('Punjab Cricket Association IS Bindra Stadium','Punjab Cricket Association Stadium') 
match['Venue']=match['Venue'].replace('Punjab Cricket Association IS Bindra Stadium, Mohali','Punjab Cricket Association Stadium') 
match['Venue']=match['Venue'].replace('Punjab Cricket Association Stadium, Mohali','Punjab Cricket Association Stadium') 
match['Venue']=match['Venue'].replace('Rajiv Gandhi International Stadium, Uppal','Rajiv Gandhi International Stadium') 
match['Venue']=match['Venue'].replace('Wankhede Stadium, Mumbai','Wankhede Stadium') 
match['Venue'].value_counts()

Venue
Wankhede Stadium                                       104
M Chinnaswamy Stadium                                   80
Eden Gardens                                            79
Arun Jaitley Stadium                                    78
MA Chidambaram Stadium                                  67
Rajiv Gandhi International Stadium                      64
Punjab Cricket Association Stadium                      56
Sawai Mansingh Stadium                                  47
Dubai International Cricket Stadium                     46
Dr DY Patil Sports Academy                              37
Maharashtra Cricket Association Stadium                 35
Sheikh Zayed Stadium                                    29
Sharjah Cricket Stadium                                 28
Brabourne Stadium                                       27
Subrata Roy Sahara Stadium                              16
Kingsmead                                               15
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium     13
Sardar Patel Stadium, Motera                            12
SuperSport Park                                         12
Saurashtra Cricket Association Stadium                  10
Himachal Pradesh Cricket Association Stadium             9
Holkar Cricket Stadium                                   9
New Wanderers Stadium                                    8
Zayed Cricket Stadium, Abu Dhabi                         8
St George's Park                                         7
Narendra Modi Stadium, Ahmedabad                         7
Newlands                                                 7
Barabati Stadium                                         7
JSCA International Stadium Complex                       7
Shaheed Veer Narayan Singh International Stadium         6
Nehru Stadium                                            5
Green Park                                               4
Vidarbha Cricket Association Stadium, Jamtha             3
De Beers Diamond Oval                                    3
Buffalo Park                                             3
OUTsurance Oval                                          2
Name: count, dtype: int64

In [8]:
teams =[
    'Sunrisers Hyderabad', 'Mumbai Indians','Royal Challengers Bangalore','Kolkata Knight Riders','Punjab Kings',
    'Chennai Super Kings', 'Rajasthan Royals', 'Delhi Capitals', 'Lucknow Super Giants', 'Gujarat Titans'
]
match['Team1']=match['Team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match['Team2']=match['Team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match['TossWinner']=match['TossWinner'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match['WinningTeam'] = match['WinningTeam'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')

match['Team1']=match['Team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match['Team2']=match['Team2'].str.replace('Delhi Daredevils','Delhi Capitals')
match['TossWinner']=match['TossWinner'].str.replace('Delhi Daredevils','Delhi Capitals')
match['WinningTeam'] = match['WinningTeam'].str.replace('Delhi Daredevils', 'Delhi Capitals')

match['Team1']=match['Team1'].str.replace('Kings XI Punjab','Punjab Kings')
match['Team2']=match['Team2'].str.replace('Kings XI Punjab','Punjab Kings')
match['TossWinner']=match['TossWinner'].str.replace('Kings XI Punjab','Punjab Kings')
match['WinningTeam'] = match['WinningTeam'].str.replace('Kings XI Punjab', 'Punjab Kings')


match['Team1']=match['Team1'].str.replace('Rising Pune Supergiants','Rising Pune Supergiant')
match['Team2']=match['Team2'].str.replace('Rising Pune Supergiants','Rising Pune Supergiant')
match['TossWinner']=match['TossWinner'].str.replace('Rising Pune Supergiants','Rising Pune Supergiant')
match['WinningTeam'] = match['WinningTeam'].str.replace('Rising Pune Supergiants','Rising Pune Supergiant')

match = match[match['Team1'].isin(teams)]
match = match[match['Team2'].isin(teams)]
match = match[match['TossWinner'].isin(teams)]
match = match[match['WinningTeam'].isin(teams)]

In [9]:
total_score = deliveries.groupby(['ID', 'innings']).sum()['total_run'].reset_index()
total_score.head()

       ID  innings  total_run
0  335982        1        222
1  335982        2         82
2  335983        1        240
3  335983        2        207
4  335984        1        129

In [10]:
total_score = total_score[total_score['innings']==1]

In [11]:
total_score['target'] = total_score['total_run'] + 1
match_df = match.merge(total_score[['ID','target']], on='ID')

In [12]:
match_df = match_df[match_df['method'].isna()]

In [13]:
match_df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,target
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,131
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,...,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,158
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,Eden Gardens,Lucknow Super Giants,field,...,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,208
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,Eden Gardens,Gujarat Titans,field,...,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,189
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,Wankhede Stadium,Sunrisers Hyderabad,bat,...,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan,158

In [14]:
deliveries['BattingTeam'] = deliveries['BattingTeam'].str.replace('Kings XI Punjab', 'Punjab Kings')
deliveries['BattingTeam'] = deliveries['BattingTeam'].str.replace('Delhi Daredevils', 'Delhi Capitals')
deliveries['BattingTeam'] = deliveries['BattingTeam'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
deliveries['BattingTeam'] = deliveries['BattingTeam'].str.replace('Rising Pune Supergiants','Rising Pune Supergiant')
deliveries  = deliveries[deliveries['BattingTeam'].isin(teams)]

In [15]:
deliveries_df =match_df.merge(deliveries,on='ID')
deliveries_df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals

In [16]:
deliveries_df.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2', 'target', 'innings', 'overs',
       'ballnumber', 'batter', 'bowler', 'non-striker', 'extra_type',
       'batsman_run', 'extras_run', 'total_run', 'non_boundary',
       'isWicketDelivery', 'player_out', 'kind', 'fielders_involved',
       'BattingTeam'],
      dtype='object')

In [17]:
deliveries_df=deliveries_df[deliveries_df['innings']==2]

In [18]:
deliveries_df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
120,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans
121,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans
122,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,1,0,1,0,0,NaN,NaN,NaN,Gujarat Titans
123,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans
124,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans

In [19]:
deliveries_df['current_score'] = deliveries_df.groupby('ID')['total_run'].cumsum()
deliveries_df['runs_left'] = deliveries_df['target']-deliveries_df['current_score']+1

In [20]:
deliveries_df['balls_left']=120-(deliveries_df['overs']*6+deliveries_df['ballnumber'])

In [21]:
deliveries_df['wickets_left'] = 10 - deliveries_df.groupby('ID')['isWicketDelivery'].cumsum()

In [22]:
deliveries_df['crr']=(deliveries_df['current_score']*6)/(120-deliveries_df['balls_left'])

In [23]:
deliveries_df['rrr']=(deliveries_df['runs_left']*6)/deliveries_df['balls_left']

In [24]:
deliveries_df = deliveries_df.reset_index()

In [25]:
def resultfun(row):
    
    return 1 if row['BattingTeam'] == row['WinningTeam'] else 0

In [26]:
deliveries_df['result'] = deliveries_df.apply(resultfun,axis=1)

In [27]:
index1 = deliveries_df[deliveries_df['Team2']==deliveries_df['BattingTeam']]['Team1'].index
index2 = deliveries_df[deliveries_df['Team1']==deliveries_df['BattingTeam']]['Team2'].index
deliveries_df.loc[index1, 'BowlingTeam'] = deliveries_df.loc[index1, 'Team1']
deliveries_df.loc[index2, 'BowlingTeam'] = deliveries_df.loc[index2, 'Team2']
deliveries_df.head()

,index,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,...,fielders_involved,BattingTeam,current_score,runs_left,balls_left,wickets_left,crr,rrr,result,BowlingTeam
0,120,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,...,NaN,Gujarat Titans,0,132,119,10,0.0,6.655462,1,Rajasthan Royals
1,121,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,...,NaN,Gujarat Titans,0,132,118,10,0.0,6.711864,1,Rajasthan Royals
2,122,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,...,NaN,Gujarat Titans,1,131,117,10,2.0,6.717949,1,Rajasthan Royals
3,123,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,...,NaN,Gujarat Titans,1,131,116,10,1.5,6.775862,1,Rajasthan Royals
4,124,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,...,NaN,Gujarat Titans,1,131,115,10,1.2,6.834783,1,Rajasthan Royals

In [28]:
final_df = deliveries_df[['BattingTeam', 'BowlingTeam', 'City','runs_left',
                        'balls_left','wickets_left','crr',
                        'rrr', 'target', 'result']]

final_df.head()

,BattingTeam,BowlingTeam,City,runs_left,balls_left,wickets_left,crr,rrr,target,result
0,Gujarat Titans,Rajasthan Royals,Ahmedabad,132,119,10,0.0,6.655462,131,1
1,Gujarat Titans,Rajasthan Royals,Ahmedabad,132,118,10,0.0,6.711864,131,1
2,Gujarat Titans,Rajasthan Royals,Ahmedabad,131,117,10,2.0,6.717949,131,1
3,Gujarat Titans,Rajasthan Royals,Ahmedabad,131,116,10,1.5,6.775862,131,1
4,Gujarat Titans,Rajasthan Royals,Ahmedabad,131,115,10,1.2,6.834783,131,1

In [29]:
final_df.shape

(95056, 10)

In [30]:
final_df.isnull().sum()

BattingTeam        0
BowlingTeam        0
City            6012
runs_left          0
balls_left         0
wickets_left       0
crr                0
rrr                2
target             0
result             0
dtype: int64

In [31]:
# dropping of null values


final_df = final_df.dropna()

final_df.isnull().sum()

BattingTeam     0
BowlingTeam     0
City            0
runs_left       0
balls_left      0
wickets_left    0
crr             0
rrr             0
target          0
result          0
dtype: int64

In [32]:
final_df = final_df[final_df['balls_left'] != 0]

In [33]:
final_df.shape

(88743, 10)

In [34]:
data = final_df.copy()

test = data['result']

train = data.drop(['result'],axis = 1)

train.head()

,BattingTeam,BowlingTeam,City,runs_left,balls_left,wickets_left,crr,rrr,target
0,Gujarat Titans,Rajasthan Royals,Ahmedabad,132,119,10,0.0,6.655462,131
1,Gujarat Titans,Rajasthan Royals,Ahmedabad,132,118,10,0.0,6.711864,131
2,Gujarat Titans,Rajasthan Royals,Ahmedabad,131,117,10,2.0,6.717949,131
3,Gujarat Titans,Rajasthan Royals,Ahmedabad,131,116,10,1.5,6.775862,131
4,Gujarat Titans,Rajasthan Royals,Ahmedabad,131,115,10,1.2,6.834783,131

In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(train,test,test_size=0.2,random_state=1)

X_train.shape,X_test.shape

((70994, 9), (17749, 9))

In [36]:
X_train.columns

Index(['BattingTeam', 'BowlingTeam', 'City', 'runs_left', 'balls_left',
       'wickets_left', 'crr', 'rrr', 'target'],
      dtype='object')

In [37]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn import metrics

In [38]:
# batting team,bowling team and city are categorical columns
# they will be converted to numeric using onehot encoder

cf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse=False,drop='first'),['BattingTeam','BowlingTeam','City'])
],remainder='passthrough')

In [39]:
# creating the pipeline


pipe1 = Pipeline(steps=[
    ('step1',cf),
    ('step2',LogisticRegression(solver='liblinear'))
])

# fitting the training data

pipe1.fit(X_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  ['BattingTeam', 'BowlingTeam',
                                                   'City'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [40]:
y_pred = pipe1.predict(X_test)
print(metrics.accuracy_score(y_test,y_pred))

0.8140740323398501

In [41]:
pipe1.predict_proba(X_test)[10]

array([0.9291909, 0.0708091])

In [42]:
# Selecting Random Forest Classifier

pipe2 = Pipeline(steps=[
    ('step1',cf),
    ('step2',RandomForestClassifier())
])

pipe2.fit(X_train,y_train)
print(metrics.accuracy_score(y_test,pipe2.predict(X_test)))

0.997802693109471

In [43]:
# oth index is loose prob and 1st index is win prob

pipe2.predict_proba(X_test)[10]

array([1., 0.])

In [45]:
# saving the logistic regression model

import pickle
pickle.dump(pipe1,open('pipe1.pkl','wb'))